-- MySQL Script generated by MySQL Workbench
-- mer. 01 avril 2015 10:21:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `rights` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `reference` VARCHAR(20) NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `type` VARCHAR(255) NULL,
  `matiere` VARCHAR(255) NULL,
  `largeur` DECIMAL NULL,
  `longueur` DECIMAL NULL,
  `hauteur` DECIMAL NULL,
  `poids` DECIMAL NULL,
  `localisation_actuelle` VARCHAR(255) NULL,
  `localisation_origine` VARCHAR(255) NULL,
  `archeologue` VARCHAR(255) NULL,
  `date_decouverte` DATETIME NULL,
  `civilisation` VARCHAR(150) NULL,
  `model3D` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`commentaire` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  `objet` INT NOT NULL,
  `utilisateur` INT NOT NULL,
  PRIMARY KEY (`id`, `objet`, `utilisateur`),
  INDEX `fk_commentaire_objet1_idx` (`objet` ASC),
  INDEX `fk_commentaire_utilisateur1_idx` (`utilisateur` ASC),
  CONSTRAINT `fk_commentaire_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commentaire_utilisateur1`
    FOREIGN KEY (`utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fait_historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fait_historique` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NOT NULL,
  `valide` TINYINT(1) NOT NULL,
  `visible` TINYINT(1) NOT NULL,
  `objet` INT NOT NULL,
  `utilisateur` INT NOT NULL,
  PRIMARY KEY (`id`, `objet`, `utilisateur`),
  INDEX `fk_fait_historique_objet1_idx` (`objet` ASC),
  INDEX `fk_fait_historique_utilisateur1_idx` (`utilisateur` ASC),
  CONSTRAINT `fk_fait_historique_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fait_historique_utilisateur1`
    FOREIGN KEY (`utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proposition_modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proposition_modification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_champ` VARCHAR(40) NOT NULL,
  `nouveau_contenu` TEXT NOT NULL,
  `objet` INT NOT NULL,
  `utilisateur` INT NOT NULL,
  PRIMARY KEY (`id`, `objet`, `utilisateur`),
  INDEX `fk_proposition_modification_objet1_idx` (`objet` ASC),
  INDEX `fk_proposition_modification_utilisateur1_idx` (`utilisateur` ASC),
  CONSTRAINT `fk_proposition_modification_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proposition_modification_utilisateur1`
    FOREIGN KEY (`utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historique` (
  `objet` INT NOT NULL,
  `utilisateur` INT NOT NULL,
  PRIMARY KEY (`objet`, `utilisateur`),
  INDEX `fk_historique_utilisateur1_idx` (`utilisateur` ASC),
  CONSTRAINT `fk_historique_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historique_utilisateur1`
    FOREIGN KEY (`utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favoris` (
  `objet` INT NOT NULL,
  `utilisateur` INT NOT NULL,
  PRIMARY KEY (`objet`, `utilisateur`),
  INDEX `fk_favoris_utilisateur1_idx` (`utilisateur` ASC),
  CONSTRAINT `fk_favoris_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoris_utilisateur1`
    FOREIGN KEY (`utilisateur`)
    REFERENCES `mydb`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parcours` (
  `id` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contenu_site`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contenu_site` (
  `place` INT NOT NULL AUTO_INCREMENT,
  `contenu` TEXT NULL,
  PRIMARY KEY (`place`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`parcours_objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`parcours_objet` (
  `parcours` INT NOT NULL,
  `objet` INT NOT NULL,
  PRIMARY KEY (`parcours`, `objet`),
  INDEX `fk_parcours_objet_objet1_idx` (`objet` ASC),
  CONSTRAINT `fk_parcours_objet_parcours1`
    FOREIGN KEY (`parcours`)
    REFERENCES `mydb`.`parcours` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parcours_objet_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oeuvre_composite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oeuvre_composite` (
  `oeuvre_principale` INT NOT NULL,
  `oeuvre_inspiree` INT NOT NULL,
  PRIMARY KEY (`oeuvre_principale`, `oeuvre_inspiree`),
  INDEX `fk_oeuvre_composite_objet1_idx` (`oeuvre_inspiree` ASC),
  CONSTRAINT `fk_oeuvre_composite_objet`
    FOREIGN KEY (`oeuvre_principale`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oeuvre_composite_objet1`
    FOREIGN KEY (`oeuvre_inspiree`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statistique_objet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statistique_objet` (
  `objet1` INT NOT NULL,
  `objet2` INT NOT NULL,
  PRIMARY KEY (`objet1`, `objet2`),
  INDEX `fk_statistique_objet_objet2_idx` (`objet2` ASC),
  CONSTRAINT `fk_statistique_objet_objet1`
    FOREIGN KEY (`objet1`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statistique_objet_objet2`
    FOREIGN KEY (`objet2`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lien` VARCHAR(255) NOT NULL,
  `objet` INT NOT NULL,
  PRIMARY KEY (`id`, `objet`),
  INDEX `fk_table1_objet1_idx` (`objet` ASC),
  CONSTRAINT `fk_table1_objet1`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`video` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lien` VARCHAR(255) NOT NULL,
  `objet` INT NOT NULL,
  PRIMARY KEY (`id`, `objet`),
  INDEX `fk_table1_objet1_idx` (`objet` ASC),
  CONSTRAINT `fk_table1_objet10`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`audio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lien` VARCHAR(255) NOT NULL,
  `objet` INT NOT NULL,
  PRIMARY KEY (`id`, `objet`),
  INDEX `fk_table1_objet1_idx` (`objet` ASC),
  CONSTRAINT `fk_table1_objet100`
    FOREIGN KEY (`objet`)
    REFERENCES `mydb`.`objet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
